Repository jfrog/jfrog-idea-plugin, pull requests merged in 2022-11, with the labels that each got.

#236 Modernize plugin
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  release/pipelines.release.yml
  src/main/java/com/jfrog/ide/idea/ci/CiManager.java
  src/main/java/com/jfrog/ide/idea/log/Logger.java
  src/main/java/com/jfrog/ide/idea/navigation/NavigationService.java
  src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
  src/main/java/com/jfrog/ide/idea/ui/CiComponentsTree.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogToolWindowFactory.java
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
  src/main/java/com/jfrog/ide/idea/ui/menus/filtermanager/CiFilterManager.java
  src/main/java/com/jfrog/ide/idea/ui/menus/filtermanager/LocalFilterManager.java
  src/main/java/com/jfrog/ide/idea/ui/utils/IconUtils.java
  src/main/resources/META-INF/plugin.xml
  src/test/java/com/jfrog/ide/idea/scan/GradleScanManagerTest.java
Labels: ignore for release

#237 Fix exception from Inspector
  src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
Labels: bug

#230 Add Frogbot to this repository
  .github/workflows/frogbot-scan-pull-request.yml
Labels: improvement

#243 Read from cache when triggering a scan by the "Refresh Scan" button
  src/main/java/com/jfrog/ide/idea/actions/RefreshLocalAction.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogToolWindowFactory.java
Labels: improvement
