Repository jfrog/jfrog-idea-plugin, pull requests merged in 2023-05, with the labels that each got.

#338 Fix display issues in Windows
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
Labels: bug, safe to test

#339 Upgrade dependencies and change notes
  build.gradle
  src/main/resources/META-INF/plugin.xml
Labels: ignore for release

#340 Load the issue details view in advance
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java
Labels: improvement, safe to test

#341 Test connection - add indication for missing URL
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
Labels: improvement

#343 Read webview resources directly from the JAR
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewResourceHandler.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewSchemeHandlerFactory.java
Labels: improvement

#349 Fix IndexNotReadyException on plugin startup
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
Labels: bug

#350 Change notes update
  src/main/resources/META-INF/plugin.xml
Labels: ignore for release, safe to test

#354 Fix inspection errors on startup
  src/main/java/com/jfrog/ide/idea/inspections/NpmInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/YarnInspection.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
  src/main/resources/META-INF/plugin.xml
Labels: bug
