Repository jfrog/jfrog-idea-plugin, pull requests merged in 2023-03, with the labels that each got.

#308 Add Integration Tests
  .github/workflows/integration-tests.yml
  build.gradle
  src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/Eos.java
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/ScanUtils.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
  src/test/java/com/jfrog/ide/idea/integration/ApplicabilityScannerIntegrationTests.java
  src/test/java/com/jfrog/ide/idea/integration/BaseIntegrationTest.java
  src/test/resources/applicability/testProjects/npm/index.js
  src/test/resources/applicability/testProjects/python/main.py
Labels: ignore for release

#310 Add expiry of 7 days for scan cache files
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
Labels: improvement

#312 Rename isCacheValid to isCacheExpired
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
Labels: ignore for release

#309 Handle JCEF is not supported error
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/jcef/message/MessagePacker.java
  src/main/java/com/jfrog/ide/idea/ui/utils/ComponentUtils.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java
Labels: bug

#314 Release preparations
  build.gradle
  src/main/resources/META-INF/plugin.xml
Labels: ignore for release

#315 JCEF issue reference in the README
  README.md
Labels: ignore for release

#305 Update the plugin description
  src/main/resources/META-INF/plugin.xml
Labels: ignore for release

#316 Support fixing Maven pom.xml plugins and handle null exception
  src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/MavenInspection.java
  src/test/java/com/jfrog/ide/idea/inspections/MavenInspectionTest.java
  src/test/resources/inspections/pom.xml
Labels: improvement

#317 Fix Go inspection NullPointerException
  src/main/java/com/jfrog/ide/idea/inspections/GoInspection.java
Labels: bug

#313 Change "IntegrationTests" to "Integration Tests"
  .github/workflows/integration-tests.yml
Labels: ignore for release, safe to test

#322 Upgrade web view to version 0.1.21
  build.gradle
  gradle.properties
Labels: safe to test

#324 NPE when SeverityReasons are missing from vulnerability
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
Labels: bug, safe to test

#326 Plugin's Toolbar Modifications
  src/main/java/com/jfrog/ide/idea/actions/GoToSettingsAction.java
  src/main/java/com/jfrog/ide/idea/actions/RefreshLocalAction.java
  src/main/java/com/jfrog/ide/idea/actions/ScanTimeLabelAction.java
  src/main/java/com/jfrog/ide/idea/actions/StartLocalScanAction.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
  src/main/resources/META-INF/plugin.xml
Labels: improvement, safe to test

#321 Remove omitted dependencies in Maven
  src/main/java/com/jfrog/ide/idea/scan/MavenScanner.java
Labels: improvement
