Repository jfrog/jfrog-idea-plugin, pull requests merged in 2023-09, with the labels that each got.

#411 Fix icons not shown properly in WebStorm
  src/main/resources/icons/criticalnotapplic.svg
  src/main/resources/icons/highnotapplic.svg
  src/main/resources/icons/lownotapplic.svg
  src/main/resources/icons/mediumnotapplic.svg
  src/main/resources/icons/unknownnotapplic.svg
Labels: bug, safe to test

#407 Ignore false secret issues
  src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
Labels: ignore for release, safe to test

#391 Show floating toolbar when results don't match source code
  src/main/java/com/jfrog/ide/idea/actions/StartLocalScanAction.java
  src/main/java/com/jfrog/ide/idea/events/AnnotationEvents.java
  src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityAnnotator.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogFloatingToolbar.java
Labels: improvement, safe to test

#413 New UI for the vulnerability details view
  gradle.properties
Labels: improvement, safe to test

#415 Improve source code scanners logging
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: improvement, safe to test

#416 Fix ERR_ABORTED when opening links
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java
Labels: bug, safe to test

#417 Upgrade Analyzer Manger to version 1.3.2.2005632
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: new feature, safe to test

#418 Upgrade Analyzer Manger to version 1.3.2.2006984
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: improvement, safe to test

#419 Fix InterruptedException in projects with large dependency trees
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
Labels: bug, safe to test

#420 Fix build not found error in CI tab
  src/main/java/com/jfrog/ide/idea/ci/CiManager.java
Labels: bug, safe to test

#421 Update Analyzer Manager version to 1.3.2.2019257
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: improvement, safe to test

#423 Fix - Scanners Failing to Run on Windows Due to Username Spaces
  build.gradle
Labels: bug, safe to test

#424 Fix errors in quick fix of vulnerable Maven dependencies
  src/main/java/com/jfrog/ide/idea/inspections/upgradeversion/UpgradeVersion.java
Labels: bug, safe to test

#425 Update ide-plugins-common to v2.2.6
  build.gradle
Labels: ignore for release, safe to test
