Repository jfrog/jfrog-idea-plugin, pull requests merged in 2023-07, with the labels that each got.

#366 Webview 0.2.1 Location object - Replace "row" with "startRow"
  src/main/java/com/jfrog/ide/idea/ui/webview/model/Location.java
Labels: ignore for release

#367 Upgrade sandbox and dependencies
  .github/workflows/test.yml
  build.gradle
  gradle.properties
  release/pipelines.release.yml
  release/pipelines.snapshot.yml
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogCiToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/utils/ComponentUtils.java
  src/main/resources/META-INF/plugin.xml
  src/test/java/com/jfrog/ide/idea/scan/DummyCircularDepPyPkgManager.java
  src/test/java/com/jfrog/ide/idea/scan/PypiScannerTest.java
  src/test/resources/gradle/wrapper/gradle/wrapper/gradle-wrapper.jar
  src/test/resources/gradle/wrapper/gradle/wrapper/gradle-wrapper.properties
  src/test/resources/gradle/wrapper/gradlew
  src/test/resources/gradle/wrapper/gradlew.bat
Labels: ignore for release, safe to test

#371 Fix IaC WebView display
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
Labels: ignore for release

#369 Add Java Contextual Analysis Support
  src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
Labels: ignore for release

#377 Fix integration tests not running in pull requests
  .github/workflows/integration-tests.yml
Labels: ignore for release, safe to test

#378 Upgrade Analyzer Manager Version to 1.2.4.1858388
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: ignore for release, safe to test

#375 Adds IaC and Secrets Documentation
  README.md
  readme-resources/iac.png
  readme-resources/secrets.png
Labels: ignore for release

#368 Quick fix UX improvements
  src/main/java/com/jfrog/ide/idea/ci/CiManager.java
  src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/GoInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/GradleGroovyInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/GradleKotlinInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/MavenInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/NpmInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/YarnInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/upgradeversion/GoUpgradeVersion.java
  src/main/java/com/jfrog/ide/idea/inspections/upgradeversion/NpmUpgradeVersion.java
  src/main/java/com/jfrog/ide/idea/inspections/upgradeversion/UpgradeVersion.java
  src/main/java/com/jfrog/ide/idea/inspections/upgradeversion/YarnUpgradeVersion.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/java/com/jfrog/ide/idea/ui/CiComponentsTree.java
Labels: improvement, safe to test

#381 UnsatisfiedLinkError on the plugin startup
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/icons/jfrog_icon.svg
Labels: bug, safe to test
