Repository jfrog/jfrog-idea-plugin, pull requests merged in 2023-11, with the labels that each got.

#432 Fixed Aarch64 support on source code scanning
  src/main/java/com/jfrog/ide/idea/scan/ScanUtils.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
Labels: bug

#434 Add .git to default exclusions
  src/main/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtils.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
Labels: improvement

#433 Support for downloading scan resources from an external repository
  .github/workflows/integration-tests.yml
  CONTRIBUTING.md
  build.gradle
  src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
  src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
  src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/IACScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/SastScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/java/com/jfrog/ide/idea/scan/SecretsScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
  src/test/java/com/jfrog/ide/idea/ServerConfigStub.java
  src/test/java/com/jfrog/ide/idea/configuration/ConfigurationTest.java
  src/test/java/com/jfrog/ide/idea/integration/ApplicabilityScannerIntegrationTests.java
  src/test/java/com/jfrog/ide/idea/integration/BaseIntegrationTest.java
  src/test/java/com/jfrog/ide/idea/integration/ExternalResourcesRepoIntegrationTests.java
  src/test/java/com/jfrog/ide/idea/integration/IACScannerIntegrationTests.java
  src/test/java/com/jfrog/ide/idea/integration/SecretsScannerIntegrationTests.java
  src/test/java/com/jfrog/ide/idea/scan/ScanBinaryExecutorTest.java
Labels: improvement

#436 Reference the new documentation site from the README
  README.md
  readme-resources/applicable.png
  readme-resources/ci-view.png
  readme-resources/connect.png
  readme-resources/create-ignore-rule.png
  readme-resources/iac.png
  readme-resources/jump-to-descriptor.png
  readme-resources/not-applicable.png
  readme-resources/run-scan-button.png
Labels: ignore for release

#439 Rename a title in the README
  README.md
Labels: ignore for release

#437 JAS scanners - Remove timeout & Enhance progress bar and include additional logging
  src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/IACScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/SastScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/SecretsScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/scan/data/ScanConfig.java
  src/test/java/com/jfrog/ide/idea/integration/ApplicabilityScannerIntegrationTests.java
  src/test/java/com/jfrog/ide/idea/integration/ExternalResourcesRepoIntegrationTests.java
  src/test/java/com/jfrog/ide/idea/integration/IACScannerIntegrationTests.java
  src/test/java/com/jfrog/ide/idea/integration/SecretsScannerIntegrationTests.java
Labels: improvement

#442 Update Analyzer Manager version to 1.4.0
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: improvement

#440 Yarn - Refactor the process of building impact graph
  build.gradle
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/java/com/jfrog/ide/idea/scan/YarnScanner.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
  src/test/java/com/jfrog/ide/idea/TestUtils.java
  src/test/java/com/jfrog/ide/idea/scan/GradleScannerTest.java
  src/test/java/com/jfrog/ide/idea/scan/PypiScannerTest.java
  src/test/java/com/jfrog/ide/idea/scan/YarnScannerTest.java
  src/test/resources/yarn/exampleYarnMonorepo/.gitignore
  src/test/resources/yarn/exampleYarnMonorepo/mobile/package.json
  src/test/resources/yarn/exampleYarnMonorepo/package-lock.json
  src/test/resources/yarn/exampleYarnMonorepo/package.json
  src/test/resources/yarn/exampleYarnMonorepo/web/package.json
  src/test/resources/yarn/exampleYarnMonorepo/yarn.lock
  src/test/resources/yarn/exampleYarnPackage/.gitignore
  src/test/resources/yarn/exampleYarnPackage/package.json
  src/test/resources/yarn/exampleYarnPackage/yarn.lock
Labels: bug

#441 Optimized impact paths building
  build.gradle
  gradle.properties
  src/main/java/com/jfrog/ide/idea/scan/MavenScanner.java
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerFactory.java
  src/main/java/com/jfrog/ide/idea/scan/SingleDescriptorScanner.java
  src/main/java/com/jfrog/ide/idea/scan/YarnScanner.java
  src/main/java/com/jfrog/ide/idea/scan/data/applications/JFrogApplicationsConfig.java
  src/main/java/com/jfrog/ide/idea/scan/utils/ImpactTreeBuilder.java
  src/main/java/com/jfrog/ide/idea/scan/utils/ScanUtils.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/ImpactGraph.java
  src/test/java/com/jfrog/ide/idea/scan/MavenScannerTest.java
  src/test/java/com/jfrog/ide/idea/scan/ScannerBaseTest.java
  src/test/java/com/jfrog/ide/idea/scan/SingleDescriptorScannerTest.java
  src/test/java/com/jfrog/ide/idea/scan/utils/ImpactTreeBuilderTest.java
Labels: improvement
