Repository jfrog/jfrog-idea-plugin, pull requests merged in 2023-08, with the labels that each got.

#379 Use SSLContext when sending usage report
  build.gradle
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
  src/main/java/com/jfrog/ide/idea/utils/Utils.java
Labels: bug

#370 Webview - Add event message passing from the Webview to the IDE
  src/main/java/com/jfrog/ide/idea/inspections/JumpToCode.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/jcef/message/MessagePacker.java
  src/main/java/com/jfrog/ide/idea/ui/jcef/message/MessagePipe.java
  src/main/java/com/jfrog/ide/idea/ui/jcef/message/MessagePipeSupport.java
  src/main/java/com/jfrog/ide/idea/ui/jcef/message/MessageType.java
  src/main/java/com/jfrog/ide/idea/ui/jcef/message/PackedMessage.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java
  src/main/java/com/jfrog/ide/idea/ui/webview/event/EventManager.java
  src/main/java/com/jfrog/ide/idea/ui/webview/event/Receiver.java
  src/main/java/com/jfrog/ide/idea/ui/webview/event/Sender.java
  src/main/java/com/jfrog/ide/idea/ui/webview/event/model/Event.java
  src/main/java/com/jfrog/ide/idea/ui/webview/event/model/IdeEvent.java
  src/main/java/com/jfrog/ide/idea/ui/webview/event/model/WebviewEvent.java
  src/main/java/com/jfrog/ide/idea/ui/webview/event/tasks/JumpToCodeTask.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/Location.java
  src/main/resources/META-INF/plugin.xml
Labels: improvement, safe to test

#359 Support login by SSO
  build.gradle
  src/main/java/com/jfrog/ide/idea/ci/CiManager.java
  src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
  src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/Utils.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java
  src/main/java/com/jfrog/ide/idea/utils/Utils.java
  src/test/java/com/jfrog/ide/idea/configuration/ConfigurationTest.java
Labels: new feature

#386 Update connection image in README
  readme-resources/connect.png
Labels: ignore for release

#387 Set min SSO version hint to 7.64.0
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
Labels: ignore for release

#385 Webview upgrade and fixes
  gradle.properties
  src/main/java/com/jfrog/ide/idea/inspections/JumpToCode.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java
  src/main/java/com/jfrog/ide/idea/ui/webview/event/EventManager.java
Labels: ignore for release, safe to test

#388 Fix applicability info not shown
  build.gradle
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
Labels: bug, safe to test

#389 Release preparations
  build.gradle
  gradle.properties
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/META-INF/pluginIcon.svg
Labels: ignore for release, safe to test

#390 Documentation and in product messaging improvements
  .frogbot/frogbot-config.yml
  README.md
  src/main/java/com/jfrog/ide/idea/log/Logger.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/resources/META-INF/plugin.xml
Labels: ignore for release

#393 Fix error when Go project has no modules
  src/main/java/com/jfrog/ide/idea/utils/GoUtils.java
Labels: bug, safe to test

#395 Fix ConcurrentModificationException in SourceCodeScannerManager
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
Labels: bug, safe to test

#401 Fix integration tests
  .github/workflows/integration-tests.yml
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: ignore for release, safe to test

#399 Fix converting file paths in Windows
  src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityWarning.java
  src/test/java/com/jfrog/ide/idea/scan/ScanBinaryExecutorTest.java
  src/test/resources/applicability/not_applic_output.sarif
  src/test/resources/applicability/simple_output.sarif
Labels: bug, safe to test

#400 Update AnalyzerManager to version 1.2.4.1921744
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: improvement, safe to test

#403 Release preparations
  build.gradle
  src/main/resources/META-INF/plugin.xml
Labels: ignore for release, safe to test

#404 Fix NPE when reading results from cache
  build.gradle
Labels: bug, safe to test

#405 Fix PluginException thrown if the Go plugin is not installed
  src/main/java/com/jfrog/ide/idea/scan/GoScanner.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
Labels: bug, safe to test

#396 Documentation improvements
  README.md
Labels: ignore for release, safe to test

#406 Migrating GlobalSettings component to a service
  src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
  src/main/resources/META-INF/plugin.xml
Labels: ignore for release, safe to test

#410 Allow only one thread to update the AnalyzerManager binary at any time
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: bug, safe to test

#409 Fix EOS CodeFlows Jump to code
  src/main/java/com/jfrog/ide/idea/scan/EosScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
  src/main/java/com/jfrog/ide/idea/ui/webview/event/tasks/JumpToCodeTask.java
Labels: ignore for release
