Repository jfrog/jfrog-idea-plugin, pull requests merged in 2023-12, with the labels that each got.

#449 Analyzer manager version update to 1.6.0
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: improvement

#450 Introducing Verification Code for SSO Login
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
Labels: improvement

#451 Dependency Upgrade: ide-plugins-common
  build.gradle
Labels: ignore for release

#452 Resolved TreeUI Error
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
Labels: bug

#455 Analyzer Manager Version Update 1.6.2
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: bug

#456 Fix release
  release/pipelines.release.yml
  release/pipelines.snapshot.yml
Labels: ignore for release

#458 Fix release
  release/pipelines.release.yml
  release/pipelines.snapshot.yml
Labels: ignore for release

#460 Fixed Go Issue in Windows with executable path containing spaces
  build.gradle
Labels: bug
