Repository jfrog/jfrog-idea-plugin, pull requests merged in 2023-02, with the labels that each got.

#282 Add indirect dependency indication
  build.gradle
  src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/SingleDescriptorScanManager.java
Labels: improvement

#281 Allow creating ignore rules to specific violation
  build.gradle
  src/main/java/com/jfrog/ide/idea/actions/CreateIgnoreRuleAction.java
  src/main/java/com/jfrog/ide/idea/ui/IssuesTableSelectionListener.java
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
Labels: improvement

#283 Restructure
  build.gradle
  src/main/java/com/jfrog/ide/idea/actions/RefreshLocalAction.java
  src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/AnnotationIconRenderer.java
  src/main/java/com/jfrog/ide/idea/inspections/AnnotationUtils.java
  src/main/java/com/jfrog/ide/idea/inspections/GoInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/GradleInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/InspectionUtils.java
  src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityAnnotator.java
  src/main/java/com/jfrog/ide/idea/inspections/MavenInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/NpmInspection.java
  src/main/java/com/jfrog/ide/idea/navigation/NavigationService.java
  src/main/java/com/jfrog/ide/idea/scan/GoScanner.java
  src/main/java/com/jfrog/ide/idea/scan/GradleScanner.java
  src/main/java/com/jfrog/ide/idea/scan/MavenScanner.java
  src/main/java/com/jfrog/ide/idea/scan/NpmScanner.java
  src/main/java/com/jfrog/ide/idea/scan/PypiScanner.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
  src/main/java/com/jfrog/ide/idea/scan/ScanUtils.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerFactory.java
  src/main/java/com/jfrog/ide/idea/scan/SingleDescriptorScanner.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/scan/YarnScanner.java
  src/main/java/com/jfrog/ide/idea/ui/ComponentsTreeCellRenderer.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogToolWindowFactory.java
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
  src/main/java/com/jfrog/ide/idea/utils/Utils.java
  src/main/resources/META-INF/plugin.xml
  src/test/java/com/jfrog/ide/idea/scan/GradleScannerTest.java
Labels: ignore for release

#284 Fix Balloon notifications not showing
  src/main/java/com/jfrog/ide/idea/log/Logger.java
  src/main/resources/META-INF/plugin.xml
Labels: bug

#287 Fix Default Excluded Paths
  src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
Labels: bug

#286 Apply Connections details change between source code scanners runs
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: bug

#285 Add Inactive Jfrog platform handling (free-tier)
  build.gradle
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
Labels: improvement

#299 Update Webview to 0.1.20
  gradle.properties
Labels: ignore for release

#297 Welcome and empty state displays
  src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
  src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScannerBase.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
  src/main/java/com/jfrog/ide/idea/ui/utils/ComponentUtils.java
Labels: improvement

#300 Fix - The applicability scan is irrelevant if no CVES were found.
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
Labels: bug

#302 Disable navigation from cached results
  build.gradle
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
Labels: bug

#303 Upgraded ide-plugins-common
  build.gradle
Labels: ignore for release

#294 New docs
  README.md
  readme-resources/applicable.png
  readme-resources/ci-settings.png
  readme-resources/ci-view.png
  readme-resources/connect.png
  readme-resources/create-ignore-rule.png
  readme-resources/jump-to-descriptor.png
  readme-resources/not-applicable.png
  readme-resources/readme_image.png
  readme-resources/run-scan-button.png
  readme-resources/vuln-details.png
  readme-resources/vuln-impact-graph.png
  src/main/java/com/jfrog/ide/idea/ui/JFrogCiToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/utils/ComponentUtils.java
  src/main/resources/META-INF/plugin.xml
Labels: improvement

#306 Fix applicability scan exclude directories
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtils.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
  src/test/java/com/jfrog/ide/idea/scan/SourceCodeManagerTest.java
Labels: bug
