Repository jfrog/jfrog-idea-plugin, pull requests merged in 2023-01, with the labels that each got.

#249 Add new applicablity scanning
  build.gradle
  src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityAnnotator.java
  src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityWarning.java
  src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/Eos.java
  src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/scan/data/ArtifactLocation.java
  src/main/java/com/jfrog/ide/idea/scan/data/CodeFlow.java
  src/main/java/com/jfrog/ide/idea/scan/data/Driver.java
  src/main/java/com/jfrog/ide/idea/scan/data/Invocation.java
  src/main/java/com/jfrog/ide/idea/scan/data/Location.java
  src/main/java/com/jfrog/ide/idea/scan/data/Message.java
  src/main/java/com/jfrog/ide/idea/scan/data/Output.java
  src/main/java/com/jfrog/ide/idea/scan/data/PhysicalLocation.java
  src/main/java/com/jfrog/ide/idea/scan/data/Region.java
  src/main/java/com/jfrog/ide/idea/scan/data/Rule.java
  src/main/java/com/jfrog/ide/idea/scan/data/Run.java
  src/main/java/com/jfrog/ide/idea/scan/data/SarifResult.java
  src/main/java/com/jfrog/ide/idea/scan/data/ScanConfig.java
  src/main/java/com/jfrog/ide/idea/scan/data/ScansConfig.java
  src/main/java/com/jfrog/ide/idea/scan/data/ThreadFlow.java
  src/main/java/com/jfrog/ide/idea/scan/data/ThreadFlowLocation.java
  src/main/java/com/jfrog/ide/idea/scan/data/Tool.java
  src/main/java/com/jfrog/ide/idea/scan/data/WorkingDirectory.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/ApplicableDetails.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/Cve.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/Evidence.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/META-INF/with-java.xml
  src/main/resources/META-INF/with-python.xml
  src/test/java/com/jfrog/ide/idea/ProgressIndicatorMock.java
  src/test/java/com/jfrog/ide/idea/scan/ScanBinaryExecutorTest.java
  src/test/java/com/jfrog/ide/idea/scan/ScanManagersTest.java
  src/test/resources/sarif/demo_output.sarif
Labels: new feature

#254 Fix missing files in results
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
Labels: ignore for release

#255 Fix windows applicability scan
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: bug

#256 Refactor tree severity icons
  build.gradle
  src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/ui/utils/IconUtils.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/icons/critical.png
  src/main/resources/icons/critical.svg
  src/main/resources/icons/default.png
  src/main/resources/icons/high.png
  src/main/resources/icons/high.svg
  src/main/resources/icons/jfrog_icon.png
  src/main/resources/icons/jfrog_icon.svg
  src/main/resources/icons/license.png
  src/main/resources/icons/low.png
  src/main/resources/icons/low.svg
  src/main/resources/icons/medium.png
  src/main/resources/icons/medium.svg
  src/main/resources/icons/normal.png
  src/main/resources/icons/notapplicable.svg
  src/main/resources/icons/security.png
  src/main/resources/icons/unknown.png
  src/main/resources/icons/unknown.svg
Labels: improvement

#257 Incorrect fixed versions in Poetry
  src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java
Labels: bug

#259 Fix JFrogSecurityAnnotator NullPointerException
  src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityAnnotator.java
Labels: bug

#261 Added ScannerSearchTarget info for the contextual analysis view
  build.gradle
  src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityWarning.java
  src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/scan/data/Message.java
  src/main/java/com/jfrog/ide/idea/scan/data/Rule.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
Labels: improvement

#258 Improve ScanBinaryExecutorTests
  src/test/java/com/jfrog/ide/idea/scan/ScanBinaryExecutorTest.java
  src/test/resources/applicability/not_applic_output.sarif
  src/test/resources/applicability/simple_output.sarif
Labels: ignore for release

#265 Support usage report with access token
  src/main/java/com/jfrog/ide/idea/utils/Utils.java
Labels: ignore for release

#266 V1 : Support usage report with access token
  src/main/java/com/jfrog/ide/idea/utils/Utils.java
Labels: ignore for release

#263 V1: Skip loading cache from file-system in full scan mode
  build.gradle
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
  src/test/java/com/jfrog/ide/idea/scan/PypiScanManagerTest.java
  src/test/java/com/jfrog/ide/idea/scan/ScanManagersTest.java
Labels: bug

#262 Fix file descriptors inspections
  src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/AnnotationIconRenderer.java
  src/main/java/com/jfrog/ide/idea/inspections/AnnotationUtils.java
  src/main/java/com/jfrog/ide/idea/inspections/GoInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/GradleGroovyInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/GradleInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/GradleKotlinInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/InspectionUtils.java
  src/main/java/com/jfrog/ide/idea/inspections/MavenInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/NpmInspection.java
  src/main/java/com/jfrog/ide/idea/inspections/ShowInDependencyTree.java
  src/main/java/com/jfrog/ide/idea/navigation/NavigationService.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
  src/main/resources/META-INF/plugin.xml
  src/main/resources/META-INF/with-go.xml
  src/main/resources/META-INF/with-groovy.xml
  src/main/resources/META-INF/with-kotlin.xml
  src/main/resources/META-INF/with-maven.xml
  src/main/resources/icons/unknown.svg
Labels: improvement

#268 Close Xray client after getting the Xray version
  src/main/java/com/jfrog/ide/idea/utils/Utils.java
Labels: bug

#260 New UI fixes
  src/main/java/com/jfrog/ide/idea/scan/GoScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/NpmScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManagersFactory.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/scan/YarnScanManager.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/ApplicableDetails.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/Cve.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/DependencyPage.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/Evidence.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/ExtendedInformation.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/ImpactedPath.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/JfrogResearchSeverityReason.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/License.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/Reference.java
  src/test/java/com/jfrog/ide/idea/scan/GradleScanManagerTest.java
  src/test/java/com/jfrog/ide/idea/scan/PypiScanManagerTest.java
  src/test/java/com/jfrog/ide/idea/scan/ScanManagersTest.java
  src/test/java/com/jfrog/ide/idea/ui/BaseTreeImpl.java
  src/test/java/com/jfrog/ide/idea/ui/ComponentsTreeTest.java
Labels: ignore for release

#278 Upgrade webview to v0.1.18
  build.gradle
  src/main/java/com/jfrog/ide/idea/ui/webview/WebviewObjectConverter.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/DependencyPage.java
  src/main/java/com/jfrog/ide/idea/ui/webview/model/ImpactGraph.java
Labels: improvement

#276 Automatically update the Webview checksum
  build.gradle
  gradle.properties
Labels: ignore for release

#277 Fix missing tests
  .github/workflows/frogbot-scan-pull-request.yml
  .github/workflows/test.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/com/jfrog/ide/idea/configuration/GlobalSettings.java
  src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
  src/main/java/com/jfrog/ide/idea/configuration/XrayServerConfigImpl.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/Utils.java
  src/test/java/com/jfrog/ide/idea/configuration/ConfigurationTest.java
  src/test/java/com/jfrog/ide/idea/inspections/GoInspectionTest.java
  src/test/java/com/jfrog/ide/idea/inspections/GradleGroovyInspectionTest.java
  src/test/java/com/jfrog/ide/idea/inspections/GradleKotlinInspectionTest.java
  src/test/java/com/jfrog/ide/idea/inspections/InspectionsTestBase.java
  src/test/java/com/jfrog/ide/idea/inspections/MavenInspectionTest.java
  src/test/java/com/jfrog/ide/idea/inspections/NpmInspectionTest.java
  src/test/java/com/jfrog/ide/idea/scan/GradleScanManagerTest.java
  src/test/java/com/jfrog/ide/idea/scan/PypiScanManagerTest.java
  src/test/java/com/jfrog/ide/idea/scan/ScanManagersTest.java
Labels: ignore for release

#272 Support exclude paths in Applicability scan
  src/main/java/com/jfrog/ide/idea/configuration/ServerConfigImpl.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtils.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/ExclusionsVerifier.java
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.form
  src/main/java/com/jfrog/ide/idea/ui/configuration/JFrogGlobalConfiguration.java
  src/test/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtilsNegativeTest.java
  src/test/java/com/jfrog/ide/idea/ui/configuration/ConfigVerificationUtilsPositiveTest.java
Labels: breaking change, improvement

#275 Reimplement jump from tree to editor
  src/main/java/com/jfrog/ide/idea/inspections/AbstractInspection.java
  src/main/java/com/jfrog/ide/idea/navigation/NavigationService.java
  src/main/java/com/jfrog/ide/idea/navigation/NavigationTarget.java
  src/main/java/com/jfrog/ide/idea/ui/ComponentsTree.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogCiToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/java/com/jfrog/ide/idea/ui/LocalComponentsTree.java
Labels: improvement

#280 Fix wrong Gradle home path
  src/main/java/com/jfrog/ide/idea/scan/GoScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/GradleScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/MavenScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/NpmScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/PypiScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/ScanManager.java
  src/main/java/com/jfrog/ide/idea/scan/YarnScanManager.java
Labels: bug

#279 Upgrade the visualization of not applicable security issues
  build.gradle
  src/main/java/com/jfrog/ide/idea/inspections/AnnotationIconRenderer.java
  src/main/java/com/jfrog/ide/idea/inspections/JFrogSecurityAnnotator.java
  src/main/java/com/jfrog/ide/idea/scan/SourceCodeScannerManager.java
  src/main/java/com/jfrog/ide/idea/ui/JFrogLocalToolWindow.java
  src/main/resources/icons/criticalnotapplic.svg
  src/main/resources/icons/highnotapplic.svg
  src/main/resources/icons/lownotapplic.svg
  src/main/resources/icons/mediumnotapplic.svg
  src/main/resources/icons/notapplicable.svg
  src/main/resources/icons/unknownnotapplic.svg
Labels: improvement

#264 Replace Applicability scanner with analyzerManager
  src/main/java/com/jfrog/ide/idea/scan/ApplicabilityScannerExecutor.java
  src/main/java/com/jfrog/ide/idea/scan/ScanBinaryExecutor.java
Labels: ignore for release
